### ISSUE TITLE
ModuleNotFoundError: No module named 'cxxfilt'

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/hpctools#28]
I think you need to add a requirements.txt with the additional Python packages you use in your tests.

**Comment by vkarak** [comment]
You should add numpy as well.

**Comment by jgphpc** [comment]
right. It's probably in the wrong place: https://github.com/eth-cscs/hpctools/blob/master/reframechecks/requirements.txt
I will move it up.

**Comment by vkarak** [comment]
I think it helps if it's at the top-level.

**Comment by jgphpc** [comment]
fixed by 5c0fa6511f8e4bd1cc937a3bd2567e1f599a8a06
